[tool.poetry]
name = "count"
version = "1.0.0"
description = "Discord bot for keeping people in sync by counting you in."
readme = "README.md"
authors = ["SeparateRecords <me@rob.ac>"]
license = "ISC"

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {version = "^1.3.4", extras = ["voice"]}
python-dotenv = "^0.14.0"
click = "^7.1.2"
black = "^19.10b0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
bot = "count:cli"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
